name: Hello World
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/helloworld.yml
  workflow_dispatch:
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-demo-codebuild-tf-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Hello world
        run: echo "Hello World ABC"
      - name: Checkout
        uses: actions/checkout@v4
